Retinanet changes
SundarRajan98/rocAL-old pull request #4
Opened 2023-10-26 07:21 UTC by fgladwin

2023-11-02 05:19 UTC, sampath-amd commented on rocAL/include/api/rocal_api_meta_data.h
> +extern "C" RocalTensorList ROCAL_API_CALL rocalGetMatchedIndices(RocalContext rocal_context);
- Correct the spelling "idices" to "indices"
- Rename rocal_context to p_context to make it consistent with previous api

2023-11-02 05:38 UTC, sampath-amd reviewed
Please address review comments

2023-11-02 05:38 UTC, sampath-amd commented on rocAL/include/pipeline/master_graph.h
> +#define MAX_ANCHORS 120087  // Num of bbox achors used in Retinanet training
Already we defined a variable MAX_NUM_ANCHORS needed SSD training
Please check if it might be better to have the variable names as MAX_SSD_ANCHORS, MAX_RETINANET_ANCHORS for better clarity?

2023-11-02 05:38 UTC, sampath-amd commented on rocAL/source/meta_data/bounding_box_graph.cpp
> +        low_quality_preds.clear();
May be we can use std::fill to reset the values for matched_vals and low_quality_preds() for each iteration?
instead of freeing the buffer and recreating it?

Please check with running some performance tests

2023-11-02 05:43 UTC, sampath-amd commented on rocAL/source/pipeline/master_graph.cpp
> +            _matches_tensor_list.push_back(new Tensor(matches_info));
Please check if we need to free memory allocated for  _matches_tensor_list when _box_iou_matcher is set to true.
Could not find this in release() function

2023-11-02 07:27 UTC, SundarRajan98 commented on rocAL/include/pipeline/master_graph.h
> +#define MAX_ANCHORS 120087  // Num of bbox achors used in Retinanet training
Align the comments

2023-11-02 07:27 UTC, SundarRajan98 commented on rocAL/include/pipeline/master_graph.h
> +    bool _is_box_iou_matcher = false; // bool variable to set the box iou matcher
Align the comments

2023-11-02 07:27 UTC, SundarRajan98 commented on rocAL/source/meta_data/bounding_box_graph.cpp
> +                    if (fabs(bbox_iou[anchor_idx] - best_bbox_iou) < 1e-6)
Is there any reason why 1e-6 is chosen for bbox_iou? State the reason if any

2023-11-02 08:49 UTC, shobiloganat requested changes

2023-11-02 08:49 UTC, shobiloganat commented on rocAL/include/pipeline/master_graph.h
> +#define MAX_ANCHORS 120087  // Num of bbox achors used in Retinanet training
Please check this. If this is going to be different please rename it accordingly for retinanet.

2023-11-02 08:49 UTC, shobiloganat commented on rocAL/source/pipeline/master_graph.cpp
> +            _matches_tensor_list.push_back(new Tensor(matches_info));
Please check this

2023-11-02 17:55 UTC, fgladwin commented on rocAL/source/meta_data/bounding_box_graph.cpp
> +        low_quality_preds.clear();
This particular code is launched in multiple threads, So each thread must have it's own resource hence it is done inside the for loop. @sampath-amd Please let me know your thoughts on this

2023-11-02 17:58 UTC, fgladwin commented on rocAL/source/pipeline/master_graph.cpp
> +            _matches_tensor_list.push_back(new Tensor(matches_info));
All the metadata tensor list will be pushed to a [vector](https://github.com/fgladwin/rocAL/blob/4ac0429f2d622fb2bb64511335d64a43fef4dc17/rocAL/source/pipeline/master_graph.cpp#L1073)
At the end all the tensor list present in the vector will be [released](https://github.com/fgladwin/rocAL/blob/4ac0429f2d622fb2bb64511335d64a43fef4dc17/rocAL/source/pipeline/master_graph.cpp#L347), which will include this matches tensor list as well.

2023-11-02 18:04 UTC, fgladwin commented on rocAL/include/api/rocal_api_meta_data.h
> +extern "C" RocalTensorList ROCAL_API_CALL rocalGetMatchedIndices(RocalContext rocal_context);
Done

2023-11-02 18:05 UTC, fgladwin commented on rocAL/include/pipeline/master_graph.h
> +#define MAX_ANCHORS 120087  // Num of bbox achors used in Retinanet training
Changed

2023-11-02 18:05 UTC, fgladwin commented on rocAL/include/pipeline/master_graph.h
> +    bool _is_box_iou_matcher = false; // bool variable to set the box iou matcher
Done

2023-11-02 18:05 UTC, fgladwin commented on rocAL/source/meta_data/bounding_box_graph.cpp
> +                    if (fabs(bbox_iou[anchor_idx] - best_bbox_iou) < 1e-6)
Added comment

2023-11-08 11:32 UTC, shobiloganat commented on rocAL/include/pipeline/master_graph.h
> +    TensorList *matched_index_meta_data();
Can you add a comment about what this returns?

2023-11-20 04:19 UTC, closed without merging